### ISSUE TITLE
Update repository description : replace « Symfony2 » by « Symfony »

### ISSUE THREAD

**Issue by Levure** [nelmio/NelmioSolariumBundle#104]
This is not really an issue, but this can cause confusion if you don't read the doc.
Shouldn't the repository description be updated to replace mention of Symfony2 by Symfony ?

Best regards,

**Comment by thePanz** [comment]
You're right! can you open a PR with that changes?

**Comment by Levure** [comment]
I did a `git clone` but I didn't find the file to edit.
If I undersrtand right, only the project owner can edit the repository description.

Am i missing something ?

**Comment by thePanz** [comment]
Oh, you're right! Sorry I misunderstood the place where Symdony2 is mentioned.

I can not edit that text, maybe @Seldaek can help here?

**Comment by Seldaek** [comment]
Done :)
