### ISSUE TITLE
PHP8

### ISSUE THREAD

**Issue by dionx** [nelmio/NelmioSolariumBundle#107]
How about support for the new version of PHP?

**Comment by VincentLanglet** [comment]
Friendly ping @thePanz ; WDYT ?

**Comment by thePanz** [comment]
@VincentLanglet @dmaicher unfortunately I have no permissions to do that on this repository :(

Only @Seldaek can change those permissions

**Comment by Seldaek** [comment]
Sent you an invite @dmaicher 👍🏻

**Comment by dmaicher** [comment]
Thanks @Seldaek 

I will start re-integrating the changes from my fork in the next days
