### ISSUE TITLE
Unrecognized option "timeout" under "nelmio_solarium.endpoints.default"

### ISSUE THREAD

**Issue by redflo** [nelmio/NelmioSolariumBundle#131]
Hi,

removing the comments about default options in config/packages/nelmio_solarium.yaml brings the above error message.

The example configuration in the symfony recipes https://github.com/symfony/recipes-contrib/tree/de3ced8/nelmio/solarium-bundle/2.4
 contains a configuration that contains a timeout parameter, which is not working when the comment hash is removed.

**Comment by dmaicher** [comment]
Fixed by https://github.com/symfony/recipes-contrib/pull/1568
