### ISSUE TITLE
New solariumphp/solarium version (3.5.0) related issue

### ISSUE THREAD

**Issue by remigarcia** [nelmio/NelmioSolariumBundle#55]
Hi,

New SolariumPHP version (3.5.0) has been released on 2015-12-09 and it changed the class name of the abstract Plugin class :
`Solarium\Core\Plugin\Plugin` => `Solarium\Core\Plugin\AbstractPlugin`

Since the `solarium/solarium` requirement in composer.json is "~3.3", the new 3.5.0 is retrieved and the Logger plugin (`Nelmio\ SolariumBundle\Logger`) tries to extends the abstract Plugin with the "old" name, which results in an error.

For now, as a workaround, we forced the version of solarium/solarium with 3.4.1 in our application composer.json.

**Comment by mgcode** [comment]
same problem here, same solution for now, waiting for fix!

**Comment by edetaillac** [comment]
+1 #sfCon2015 ;)

**Comment by jspaeth** [comment]
See PullRequest: https://github.com/nelmio/NelmioSolariumBundle/pull/56

**Comment by Seldaek** [comment]
Please use `composer require solarium/solarium:3.4.1` as a workaround for now. This is not something we should fix here, as if I merge #56 it will just mean that the bundle isn't compatible with solarium versions 3.3/3.4 anymore. See https://github.com/solariumphp/solarium/issues/382 for an issue on solarium asking for them to fix their BC break (which I guess wasn't intentional..).

**Comment by meshenka** [comment]
same here, i will do the 3.4.1 require

**Comment by anrizal** [comment]
Hello,

I tried "composer require solarium/solarium:3.4.1" also tried to change the composer.json manually, but It still fails. 

The error was
"The requested package nelmio/solarium-bundle could not be found in any version, there may be a typo in the package name."

**Comment by jspaeth** [comment]
Conposer must require solarium and the nelmioSolariumBundle. Then remove the old solarium package from the vendors directory and reinstall it by composer install or update

**Comment by Seldaek** [comment]
3.5.1 fixed it
