### ISSUE TITLE
Logger does not distinguish between multiple clients

### ISSUE THREAD

**Issue by jovobe** [nelmio/NelmioSolariumBundle#59]
If You use more than one client, the initPluginType-Function of the Logger is called multiple times (one time for each client) and it registers itself multiple times for the preExecuteRequest and postExecuteRequest event. Thereby the postExecuteRequest event is triggered twice and on the second call the $this->currentRequest is null so it throws a \RuntimeException.
This bug was "enabled" since #58.

**Comment by lutangar** [comment]
I also ran into this issue, resulting in the following exception:
> Request not set

I'm sticking to this commit for now: [036c99ee2755991c9b40f94f9a956300296f8a80](https://github.com/nelmio/NelmioSolariumBundle/tree/036c99ee2755991c9b40f94f9a956300296f8a80)

**Comment by Seldaek** [comment]
Can you please try with latest from master / `^2.2@dev` and confirm if it is fixed?

**Comment by jovobe** [comment]
@Seldaek fix confirmed!
