### ISSUE TITLE
404 Exception if no endpoints are configured

### ISSUE THREAD

**Issue by Dword123** [nelmio/NelmioSolariumBundle#60]
Hey,

if no endpoints are configured in config.yml, a 404 Exception is thrown, stating that the request handler cannot be accessed. Reason: Not found. It would be more helpful if the programmer would be notified that no endpoints are defined (or that the config is missing). Would make the implementation more robust since it takes some time to find the error source.

Thanks in advance!

**Comment by Seldaek** [comment]
I agree it'd be nice, but it's not really high priority. If someone contributes it though I'm all for it :)

**Comment by Dword123** [comment]
Hey,
just saw that you switch to a default endpoint if no explicit endpoint is specified by the user. Replacing that by an exception in exceptionRequest() would solve the issue but I'm not sure if this is your intended behavior? If so I could create a pull request. Do you have reasons for a default endpoint instead of a thrown error?

**Comment by Seldaek** [comment]
Oh I see, well I guess because most people just run it on localhost with default config, that usually works fine. Throwing without config will cause problems for people that use the default right now so I don't think we can really change that.

**Comment by Dword123** [comment]
Alright then we leave it like that! Thanks anyway.
