### ISSUE TITLE
Solarium Result is not serializable since 2.2.1

### ISSUE THREAD

**Issue by OndraM** [nelmio/NelmioSolariumBundle#62]
Hi, we are in our application caching results of the request to  Solarium (in the Result class). And the Result class from Solarium library [has reference](https://github.com/solariumphp/solarium/blob/master/library/Solarium/Core/Query/Result/Result.php#L86) to Solarium Client.

Since version 2.2.1 of the SolariumBundle the Client [has reference](https://github.com/nelmio/NelmioSolariumBundle/commit/fede21be1af5b81aeffd9c759dc4dec4f137bed3) to Symfony Event Dispatcher service, which has reference to Symfony DIC, which has again reference to the Event Dispatcher etc. As we are caching serialized instance of the Result class, these cyclic references make the serialization not working.

Do you propose any solution?

I should also note that at least for us this was serious and a bit surprising BC (as this change was released as patch version).

Thanks

**Comment by pavel-batecko** [comment]
Relevant: https://github.com/solariumphp/solarium/pull/424

**Comment by dmaicher** [comment]
Not an issue caused by this bundle and should be resolved now on Solarium
