### ISSUE TITLE
Improve load_balancer documentation

### ISSUE THREAD

**Issue by fredleger** [nelmio/NelmioSolariumBundle#68]
Looking in the it seems there is an option about load_balancer. Trying to have a 2 instances SOLR cluster i was interested but didn't succeed to make it work. 

The stange thing is there is no doc about it. Can you add a small sample of such config ?

**Comment by Seldaek** [comment]
Could it be the endpoint stuff? https://github.com/nelmio/NelmioSolariumBundle#multiple-clients-and-endpoints Sorry but I haven't used that, and haven't followed latest development in Solarium.
