### ISSUE TITLE
Symfony 3.4/4.0 support : missing reset() method on \Nelmio\SolariumBundle\Logger

### ISSUE THREAD

**Issue by gnutix** [nelmio/NelmioSolariumBundle#78]
On a freshly updated Symfony 3.4-beta3 project, I get the following deprecation notice : 

```
Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without
the "reset()" method is deprecated since version 3.4 and will be unsupported in 4.0 for
class "Nelmio\SolariumBundle\Logger"
```

**Comment by shieldo** [comment]
Support for this has now been added: https://github.com/nelmio/NelmioSolariumBundle/commit/cc139642a275827f8eb07c4751445f68fa5ae5e9

**Comment by thePanz** [comment]
Closing as fixed :)
Thanks @shieldo for noticing!

**Comment by thePanz** [comment]
@gnutix can you try the latest v3.0.0-beta release?

**Comment by gnutix** [comment]
No notices anymore. :)

**Comment by mpdude** [comment]
Do you think we could backport this to a stable 2.x?

**Comment by thePanz** [comment]
@mpdude I backported 2 fixes from the `master` branch, can you try using this branch?
https://github.com/nelmio/NelmioSolariumBundle/tree/2.4

**Comment by mpdude** [comment]
Wow, I did not expect a response that fast, thank you!

The error message from 👆🏻is now gone, great.

Yet, I get another one:

`The "Nelmio\SolariumBundle\Logger" class extends "Solarium\Core\Plugin\Plugin" that is deprecated.`

You fixed that in a06e5c1fa3f4287b0520ffa62afb81fd44578fe2. Could you backport that as well?

**Comment by thePanz** [comment]
@mpdude IIRC the difference between 3.x and the 2.4 branch is the change of the `dsn` configuration. Can you try to update your conf and use the 3.x release? :)

**Comment by mpdude** [comment]
Major version updates always scare the hell out of me :-). Besides that, if I am not missing something, there is no stable 3.0.0 yet?

Anyway, will give it a try.

**Comment by mpdude** [comment]
:+1: Works.

What do you think – is a stable 3.0 release somewhere near?

**Comment by thePanz** [comment]
I've been using v3 for a while now, no issues to report.
Apart from that, could you give it longer try? If everything work fine for you too, I'll tag a first `3.0.0` release. But let's move the discussion here: https://github.com/nelmio/NelmioSolariumBundle/issues/90
