### ISSUE TITLE
solarium 4 support?

### ISSUE THREAD

**Issue by dmaicher** [nelmio/NelmioSolariumBundle#82]
Will the next major release also support solarium 4 as well? :blush: 

I just tried it using my fork and it works nicely: https://github.com/nelmio/NelmioSolariumBundle/compare/master...dmaicher:solarium-4?expand=1

**Comment by thePanz** [comment]
I can confirm that the bundle works with the v4.0 of the solarium library.
No breaking changes have been introduced between the 3.8 and the 4.0 releases

**Comment by Seldaek** [comment]
Updated master branch but I'll let you tag a 3.0 stable when you feel it's fine @thePanz :)

**Comment by thePanz** [comment]
Thanks @Seldaek !
I think it is fine for now to have it just in the master branch.
I'd like to have a look at the failing CI, but I had no time yet

**Comment by jeroenherczeg** [comment]
Is it possible to open this again?
I use this bundle and solarium 4.1.0 has just been released.

Would be great to have this fix, if you need help, please let me know! Thank you.

**Comment by thePanz** [comment]
@jeroenherczeg this issue is closed as the latest `master` supports solarium `^4.0` :)

I will tag a `3.0.0-beta.2` release for you to further test the bundle with the newest. Is it OK for you?

**Comment by jeroenherczeg** [comment]
That would be perfect, thank you!
I will report back how it goes.
