### ISSUE TITLE
symfony 4.0 services

### ISSUE THREAD

**Issue by micheledibenedetto7** [nelmio/NelmioSolariumBundle#85]
i got this error if i try to simply use the default solarium client:

_The "solarium.client" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead._

my code in a standard controller action:
`$client = $this->get('solarium.client');`

what can i do about this? thanks in advance.

**Comment by tdierolf** [comment]
Add this to your services.yml:

```
    my.solarium.client:
        alias: solarium.client
        public: true
```

Then use `$client = $this->get('my.solarium.client');` to access the client in your controller.

**Comment by micheledibenedetto7** [comment]
> Add this to your services.yml:
> 
> ```
>     my.solarium.client:
>         alias: solarium.client
>         public: true
> ```
> 
> Then use `$client = $this->get('my.solarium.client');` to access the client in your controller.

thank you very much, works fine!
