### ISSUE TITLE
Referencing controllers with NelmioApiDocBundle:ApiDoc:index is deprecated since Symfony 4.1

### ISSUE THREAD

**Issue by ahmed-bhs** [nelmio/NelmioSolariumBundle#86]
> 
>   1x: Referencing controllers with NelmioApiDocBundle:ApiDoc:index is deprecated since Symfony 4.1, use "Nelmio\ApiDocBundle\Controller\ApiDocController::indexAction" instead.
>     1x in GetArticlesControllerTest::testAsAnonymous from App\Tests\Article
>

**Comment by dmaicher** [comment]
And this issue is on the correct repository? Seems it should be here instead? https://github.com/nelmio/NelmioApiDocBundle
