### ISSUE TITLE
Release v3.0.0

### ISSUE THREAD

**Issue by thePanz** [nelmio/NelmioSolariumBundle#90]
As discussed with @mpdude in https://github.com/nelmio/NelmioSolariumBundle/issues/78#issuecomment-482513063, let's tag a first stable `v3.0.0` release

**Comment by msphn** [comment]
Can I help here with something? I'm atm using dev-master, since I'd like using core-admin stuff. If any help or a little test is missing just ping me!

**Comment by thePanz** [comment]
I will tag a `3.0.0` release asap.
Please keep in mind that we support `"solarium/solarium": "^4.0 < 4.3.0"` only (as `solarium` v4.3 introduced some breaking changes IIRC)

**Comment by msphn** [comment]
Yeah, solarium 4.3 is fine! And the bundle is a great help :-) 👍

**Comment by thePanz** [comment]
[v3.0.0](https://github.com/nelmio/NelmioSolariumBundle/releases/tag/v3.0.0) is now released!

@msphn 4.3 is not supported, only up to `4.2.*` (see 73a6854)
