### ISSUE TITLE
Solarium 5 support?

### ISSUE THREAD

**Issue by dmaicher** [nelmio/NelmioSolariumBundle#92]
It would be nice to support Solarium 5.

As far as I can see the only issue should be the change for the default path?

https://github.com/nelmio/NelmioSolariumBundle/compare/master...dmaicher:solarium_5_compat?expand=1

I tried this on my project and it works without any other adjustments with solarium 5.0.3.
But that's because I don't set the `path` option on my project, so it uses the new default then.

So here my question: **Should we support both Solarium < 5 and 5**? If so maybe we can adjust the default config option (or maybe add a normalizer that strips out any `/solr` prefix) based on the used Solarium version? Not sure if there is a reliable way of detecting which Solarium version is used?

**Or can we release a new major (4.0.0) that will only support Solarium 5?** 

I'm willing to contribute if we agree on an approach :blush:

**Comment by dmaicher** [comment]
@Seldaek @thePanz any feedback on this? :blush:

**Comment by thePanz** [comment]
@dmaicher I like your proposal of having a new major version (4.0.0), only supporting Solarium 5 :+1: 

Feel free to create a PR for that :)
